### ISSUE TITLE
pydantic DateTime type

### ISSUE THREAD

**Issue by j30ng** [app-sre/qenerate#67]
Hi all.

I'm getting errors for datetime fields in the generated python code, because `DateTime` is not a python primitive type nor a pydantic type.

https://github.com/app-sre/qenerate/blob/7a544a9d3fadcce5465b88522c77c35b70f3c988/qenerate/plugins/pydantic_v1/mapper.py#L42

**Comment by fishi0x01** [comment]
Hi :wave:

You are right. My understanding is this should be `datetime` and we need to add `from datetime import datetime` to the generated code. Let me know if you think there is a more appropriate date type for this.

Thank you for reaching out about this!

**Comment by fishi0x01** [comment]
Ive opened a PR with a fix and added a [test case](https://github.com/app-sre/qenerate/pull/68/files#diff-af417d88b368fec3f1ed31cf9cecbe15ded20f75850144409e8962a14c98d183R36) that uses datetime. Will merge and make a release later today.

**Comment by fishi0x01** [comment]
Released version `0.4.6`. Please let me know if it didn't solve the issue.

**Comment by fishi0x01** [comment]
I gave this some more thought and given that `DateTime` is not a native GraphQL primitive, it might be a bad idea to actually convert it to `datetime.datetime`. `DateTime` is a custom scalar that might be defined differently depending on the schema. Im leaning now more towards casting all custom scalars to `str` instead - that makes it more compatible towards all schemas.
