### ISSUE TITLE
Working with fields that start with an underscore

### ISSUE THREAD

**Issue by PORTB** [app-sre/qenerate#88]
Hi, I am interacting with a graphql endpoint (not under my control) that has a field that begins with an underscore, my query looks similar to this:
```gql
# qenerate: plugin=pydantic_v1

query MyQuery {
    foobars {
      _id  # <-------------
      name
      other_stuff
    }
}
```
And pydantic throws an error with this:
``NameError: Fields must not use names with leading underscores; e.g., use 'id' instead of '_id'.``

Is there a workaround for this?

**Comment by fishi0x01** [comment]
Hi :wave: 

I dont think there is a workaround in place for that. This is a special case that needs to be addressed in this function https://github.com/app-sre/qenerate/blob/main/qenerate/plugins/pydantic_v1/mapper.py#L54

**Comment by fishi0x01** [comment]
Latest version `0.6.4` should work now. In your specific case it would result in field name `q_id` (note, that we consider `id` a reserved keyword, so we prepend it with `q_`. See https://github.com/app-sre/qenerate/blob/main/qenerate/plugins/pydantic_v1/mapper.py#L7)

Please re-open this issue if you still witness any problems.
